# Generated by Django 3.0.5 on 2020-04-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=128, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('number_of_page', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(to='book_reviews.Category')),
            ],
        ),
    ]
